// The artefacts of a signed bundle (packaging design, section 6.2, steps 7 to 9): notarise and staple
// the .app (through @electron/notarize with a keychain PROFILE NAME, never a credential), a DMG with an
// Applications link (hdiutil), signed, notarised and stapled itself, a ZIP of the stapled app (ditto),
// and the Gatekeeper checks (spctl, stapler validate, codesign --verify), all recorded in a report.
// Run from the repo root:
//   pnpm --dir app package:artefacts -- --flavour internal [--notarize <profile name>] [--out <dir>]
// Without --notarize an internal build gets its DMG and ZIP unnotarised (the owner's own machine, or
// a layout check); a release build refuses. Nothing here reads, prints or stores a secret.
//
// Pure decisions above the line (tested in artefacts.test.ts); nothing runs at import.
import {execFileSync, spawnSync} from "node:child_process";
import {createHash} from "node:crypto";
import {chmodSync, closeSync, existsSync, mkdirSync, mkdtempSync, openSync, readFileSync, readSync, renameSync, rmdirSync, rmSync, statSync, symlinkSync, writeFileSync} from "node:fs";
import {homedir, tmpdir} from "node:os";
import {basename, dirname, join, posix} from "node:path";
import {fileURLToPath} from "node:url";
import {apparmorProfile, checkPackageListing, dependsFor, desktopEntry, installDir, linuxArtefactDecision, NFPM, nfpmConfig, nfpmVersionOf, parseDebListing, parseNeeded, parseRpmListing, pngSize,
  postinstScript, prermScript} from "./linux/packages.mjs";
import {walk} from "./walk.mjs";
import {BUNDLE_IDS, requestedFlavour, resolveOut} from "./stage.mjs";

/**
 * `Clave-Agent-Internal-0.1.0-20260922.0815-arm64`: the app name without spaces, the version, the build
 * number, the architecture (`x64` for the Windows build).
 */
export function artefactBaseName(info, arch = "arm64") {
  if (!info || typeof info.appName !== "string" || !info.appName.trim() || typeof info.version !== "string" || typeof info.buildNumber !== "string") return null;
  const name = info.appName.trim().split(/\s+/).join("-").replace(/[^A-Za-z0-9.-]/g, "");
  if (!name) return null;
  return `${name}-${info.version}-${info.buildNumber}-${arch}`;
}

// ---------------------------------------------------------------------------------------------
// Windows: an Inno Setup installer and a ZIP of the app folder.

/**
 * Inno Setup's AppId per flavour: what Windows files the install under in Apps & features, and how a
 * newer installer recognises the older install it upgrades. PERMANENT: changing one makes the next
 * version install beside the old one instead of over it. Generated once on 2026-09-23.
 */
export const INSTALLER_APP_IDS = {internal: "A8670C1C-E426-458C-A43C-79AA5B652C60", release: "C2EDC4C4-FB80-4F50-A645-04DCA45A2DD1"};

/**
 * Windows.Graphics.Capture, which the reader captures with, arrived in Windows 10 version 1903
 * (build 18362): the installer refuses anything older rather than install an app that cannot read.
 */
export const WINDOWS_MIN_VERSION = "10.0.18362";

/** A value for an Inno Setup script line: quotes doubled, and no line break or control character at all. */
export function innoValue(value) {
  const text = String(value);
  if (/[\x00-\x1f]/.test(text)) throw new Error("INNO_VALUE_CONTROL_CHARACTER");
  return text.split('"').join('""');
}

/**
 * The whole Inno Setup script for one Windows app folder. Pure, so what the tests read is what ISCC
 * compiles. The install is per user (`PrivilegesRequired=lowest`: no administrator prompt, installed
 * under %LOCALAPPDATA%\Programs), its Start menu shortcut carries the app's AppUserModelID (without
 * it Windows shows none of the app's notifications), a running copy is closed before files are
 * replaced, and the previous version's resources are removed first so no stale file survives an
 * upgrade. Uninstalling removes the app and leaves the user's data, as on macOS.
 */
export function innoScript({flavour, appName, version, fileVersion, publisher, appUserModelId, sourceDir, iconPath, outputDir, outputBaseName}) {
  const appId = Object.hasOwn(INSTALLER_APP_IDS, flavour) ? INSTALLER_APP_IDS[flavour] : null;
  if (appId === null) throw new Error("INSTALLER_FLAVOUR_UNKNOWN");
  const v = innoValue;
  const exe = `${appName}.exe`;
  return [
    "; Generated by app/scripts/package/artefacts.mjs (innoScript). Do not edit: change the generator.",
    "[Setup]",
    // Inno's `{{` is a literal brace: the AppId is written as {GUID}.
    `AppId={{${appId}}`,
    `AppName=${v(appName)}`,
    `AppVersion=${v(version)}`,
    `AppVerName=${v(appName)} ${v(version)}`,
    `AppPublisher=${v(publisher)}`,
    `VersionInfoVersion=${v(fileVersion)}`,
    `VersionInfoProductName=${v(appName)}`,
    `DefaultDirName={autopf}\\${v(appName)}`,
    "DisableDirPage=auto",
    "DisableProgramGroupPage=yes",
    "PrivilegesRequired=lowest",
    "ArchitecturesAllowed=x64compatible",
    "ArchitecturesInstallIn64BitMode=x64compatible",
    `MinVersion=${WINDOWS_MIN_VERSION}`,
    `SetupIconFile=${v(iconPath)}`,
    `UninstallDisplayIcon={app}\\${v(exe)}`,
    `UninstallDisplayName=${v(appName)}`,
    "CloseApplications=yes",
    "RestartApplications=no",
    "Compression=lzma2/max",
    "SolidCompression=yes",
    "WizardStyle=modern",
    `OutputDir=${v(outputDir)}`,
    `OutputBaseFilename=${v(outputBaseName)}`,
    "",
    "[Languages]",
    'Name: "english"; MessagesFile: "compiler:Default.isl"',
    "",
    "[InstallDelete]",
    'Type: filesandordirs; Name: "{app}\\resources"',
    'Type: filesandordirs; Name: "{app}\\locales"',
    "",
    "[Files]",
    `Source: "${v(sourceDir)}\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs`,
    "",
    "[Icons]",
    `Name: "{autoprograms}\\${v(appName)}"; Filename: "{app}\\${v(exe)}"; AppUserModelID: "${v(appUserModelId)}"`,
    "",
    "[Run]",
    `Filename: "{app}\\${v(exe)}"; Description: "Open ${v(appName)}"; Flags: nowait postinstall skipifsilent`,
    ""
  ].join("\r\n");
}

/**
 * What a Windows artefacts run may be made from. The bundle must have been through the fuse step; a
 * release must also be signed, which on Windows is not set up yet (owner decision, 2026-09-23: unsigned
 * for now), so today only an internal build gets artefacts.
 */
export function windowsArtefactDecision({flavour, report}) {
  if (flavour !== "internal" && flavour !== "release") return {error: "BAD_FLAVOUR"};
  if (!report || report.platform !== "win32") return {error: "BUNDLE_NOT_WINDOWS"};
  if (report.fused !== true) return {error: "ARTEFACT_NEEDS_FUSED"};
  if (flavour === "release" && report.signed !== true) return {error: "ARTEFACT_NEEDS_SIGNED"};
  return {ok: true};
}

/** The ZIP of the app folder, by Windows' own bsdtar (`tar -a` picks the format from `.zip`). */
export function winZipCommand({bundleDir, folderName, zipPath}) {
  return ["tar.exe", ["-a", "-c", "-f", zipPath, "-C", bundleDir, folderName]];
}

/** `--notarize <profile>` from argv; the `=` spelling and repeats refuse; the value is a keychain profile NAME. */
export function parseNotarizeArg(argv) {
  const spellings = argv.filter((a) => typeof a === "string" && a.startsWith("--notarize"));
  if (spellings.length === 0) return {profile: null};
  if (spellings.length > 1 || spellings[0] !== "--notarize") return {error: "BAD_NOTARIZE"};
  const value = argv[argv.indexOf("--notarize") + 1];
  if (typeof value !== "string" || !value.trim() || value.startsWith("-")) return {error: "BAD_NOTARIZE"};
  return {profile: value.trim()};
}

/**
 * Whether this run notarises, and why not. Only a bundle signed under a Developer ID can be
 * notarised; a release build must be; an internal build may skip it.
 */
export function notarizeDecision({flavour, report, profile}) {
  if (flavour !== "internal" && flavour !== "release") return {error: "BAD_FLAVOUR"};
  if (!report || report.signed !== true) return {error: "ARTEFACT_NEEDS_SIGNED"};
  if (profile === null || profile === undefined) return flavour === "release" ? {error: "NOTARIZE_REQUIRED"} : {skip: true};
  if (report.developerId !== true) return {error: "NOTARIZE_NEEDS_DEVELOPER_ID"};
  return {profile};
}

export function dmgCommand({root, volumeName, dmgPath}) {
  return ["/usr/bin/hdiutil", ["create", "-volname", volumeName, "-srcfolder", root, "-ov", "-format", "UDZO", "-fs", "HFS+", "-quiet", dmgPath]];
}

export function zipCommand({appPath, zipPath}) {
  return ["/usr/bin/ditto", ["-c", "-k", "--keepParent", appPath, zipPath]];
}

export function copyAppCommand({appPath, destAppPath}) {
  return ["/usr/bin/ditto", [appPath, destAppPath]];
}

export function signDmgCommand({identity, dmgPath}) {
  return ["/usr/bin/codesign", ["--sign", identity, "--timestamp", "--force", dmgPath]];
}

export function notarySubmitCommand({path, profile}) {
  return ["/usr/bin/xcrun", ["notarytool", "submit", path, "--keychain-profile", profile, "--wait", "--output-format", "json"]];
}

/** The notary log of one submission, saved next to the artefacts so a rejection has its reasons on file. */
export function notaryLogCommand({id, profile}) {
  return ["/usr/bin/xcrun", ["notarytool", "log", id, "--keychain-profile", profile]];
}

/**
 * The outcome of a `submit --wait`: `{status, id}` from notarytool's JSON output, or from its text
 * form as a fallback (stdout and stderr merged by the caller). Status is one of Accepted, Invalid,
 * Rejected, In Progress, or null when nothing readable came back.
 */
export function notaryResult(output) {
  const text = String(output ?? "");
  try {
    const parsed = JSON.parse(text.trim());
    if (parsed && typeof parsed === "object") {
      const status = ["Accepted", "Invalid", "Rejected", "In Progress"].includes(parsed.status) ? parsed.status : null;
      return {status, id: typeof parsed.id === "string" ? parsed.id : null};
    }
  } catch { /* not JSON: the text form */ }
  const id = /^\s*id:\s*([0-9a-fA-F-]{8,})\s*$/m.exec(text);
  return {status: notaryStatus(text), id: id ? id[1] : null};
}

/** `Authority=` lines and the `TeamIdentifier=` of a `codesign -dvv` description (names only, never a hash). */
export function signatureChain(dvvOutput) {
  const text = String(dvvOutput ?? "");
  const authorities = [...text.matchAll(/^Authority=(.+)$/gm)].map((m) => m[1].trim());
  const team = /^TeamIdentifier=(.+)$/m.exec(text);
  return {authorities, teamIdentifier: team ? team[1].trim() : null};
}

export function stapleCommand(path) {
  return ["/usr/bin/xcrun", ["stapler", "staple", path]];
}

/** The status word of a `notarytool submit --wait` transcript: `Accepted`, `Invalid`, `Rejected`, or null. */
export function notaryStatus(output) {
  const m = /^\s*status:\s*(Accepted|Invalid|Rejected|In Progress)\s*$/m.exec(String(output));
  return m ? m[1] : null;
}

/**
 * The checks and what each must do. `mustPass` is decided by what the bundle is: a self-signed
 * internal build cannot pass Gatekeeper and is not expected to; a notarised one must.
 */
export function checkPlan({appPath, dmgPath, developerId, notarized}) {
  return [
    {name: "codesign-verify-app", cmd: "/usr/bin/codesign", args: ["--verify", "--deep", "--strict", "--verbose=2", appPath], mustPass: true},
    {name: "codesign-verify-dmg", cmd: "/usr/bin/codesign", args: ["--verify", "--verbose=2", dmgPath], mustPass: true},
    {name: "spctl-app", cmd: "/usr/sbin/spctl", args: ["--assess", "--type", "execute", "-vv", appPath], mustPass: developerId && notarized},
    {name: "spctl-dmg", cmd: "/usr/sbin/spctl", args: ["--assess", "--type", "open", "--context", "context:primary-signature", "-vv", dmgPath], mustPass: developerId && notarized},
    {name: "stapler-validate-app", cmd: "/usr/bin/xcrun", args: ["stapler", "validate", appPath], mustPass: notarized},
    {name: "stapler-validate-dmg", cmd: "/usr/bin/xcrun", args: ["stapler", "validate", dmgPath], mustPass: notarized}
  ];
}

/** Turns check results `{name, status, mustPass}` into problems. */
export function checkProblems(results) {
  return results.filter((r) => r.mustPass && r.status !== 0).map((r) => ({code: "ARTEFACT_CHECK_FAILED", detail: r.name}));
}

// ---------------------------------------------------------------------------------------------
// The impure half. Nothing below runs at import.

const sha256 = (path) => createHash("sha256").update(readFileSync(path)).digest("hex");

function run(cmd, args) {
  const r = spawnSync(cmd, args, {stdio: ["ignore", "pipe", "pipe"]});
  return {status: r.status, stdout: String(r.stdout ?? ""), stderr: String(r.stderr ?? "")};
}

async function loadNotarize() {
  const {createRequire} = await import("node:module");
  const req = createRequire(import.meta.url);
  return import(createRequire(req.resolve("@electron/packager")).resolve("@electron/notarize"));
}

/** Where ISCC is: CLAVE_ISCC, else Inno Setup 6's per-user and per-machine install folders. */
function findIscc(env) {
  const candidates = [env.CLAVE_ISCC, env.LOCALAPPDATA && join(env.LOCALAPPDATA, "Programs", "Inno Setup 6", "ISCC.exe"),
    env["ProgramFiles(x86)"] && join(env["ProgramFiles(x86)"], "Inno Setup 6", "ISCC.exe"), env.ProgramFiles && join(env.ProgramFiles, "Inno Setup 6", "ISCC.exe")];
  return candidates.find((p) => typeof p === "string" && existsSync(p)) ?? null;
}

/**
 * The Windows artefacts: the installer and the ZIP, made in a partial folder and renamed into place,
 * exactly as the macOS DMG and ZIP are. Unsigned for now (owner decision, 2026-09-23), which the
 * report says in so many words so nobody mistakes the installer for a signed one.
 */
async function windowsArtefacts({appDir, out, flavour, report, env, log, fail}) {
  const decision = windowsArtefactDecision({flavour, report});
  if (decision.error) return fail(decision.error);
  const appPath = join(out.dir, report.appPath);
  const exe = join(appPath, report.executable ?? `${report.appName}.exe`);
  if (!existsSync(exe)) return fail("BUNDLE_MISSING", "app");
  const base = artefactBaseName(report, "x64");
  if (base === null) return fail("BUNDLE_MISSING", "report fields");
  const {bundleIdFor, windowsFileVersion} = await import("./bundle.mjs");
  const appUserModelId = bundleIdFor(flavour);
  const fileVersion = windowsFileVersion(report.version);
  if (appUserModelId === null || fileVersion === null) return fail("BUNDLE_MISSING", "report fields");
  const iconPath = join(appDir, "build", "icon.ico");
  if (!existsSync(iconPath)) return fail("ICON_MISSING", "run: powershell -File app/scripts/package/make-icon.ps1");
  const iscc = findIscc(env);
  if (iscc === null) return fail("ISCC_MISSING", "install Inno Setup 6 or set CLAVE_ISCC");

  const artefactDir = join(out.dir, flavour, "artefacts");
  const partial = join(out.dir, flavour, "artefacts.partial");
  rmSync(partial, {recursive: true, force: true});
  mkdirSync(partial, {recursive: true});
  const setupBase = `${base}-setup`;
  const issPath = join(partial, `${setupBase}.iss`);

  // ISCC is not long-path aware, and node-llama-cpp's deepest file is 173 characters below the app
  // folder: under a checkout in Documents that passes Windows' 260-character limit. So ISCC reads the
  // folder through a directory junction with a short path (no administrator rights needed for one).
  // It is removed with a NON-recursive rmdir, which removes a link and refuses a real folder, so the
  // app it points at can never be deleted by this cleanup.
  const link = join(mkdtempSync(join(tmpdir(), "clave-iscc-")), "app");
  symlinkSync(appPath, link, "junction");
  let r;
  try {
    writeFileSync(issPath, innoScript({flavour, appName: report.appName, version: report.version, fileVersion, publisher: env.CLAVE_COPYRIGHT_ENTITY ?? "Clave",
      appUserModelId, sourceDir: link, iconPath, outputDir: partial, outputBaseName: setupBase}));
    r = run(iscc, ["/Q", issPath]);
  } finally {
    rmdirSync(link);
    rmdirSync(dirname(link));
  }
  if (r.status !== 0) {
    writeFileSync(join(partial, "iscc.log"), `${r.stdout}\n${r.stderr}`);
    return fail("INSTALLER_FAILED", "see artefacts.partial/iscc.log");
  }
  const installerPath = join(partial, `${setupBase}.exe`);
  if (!existsSync(installerPath)) return fail("INSTALLER_FAILED", "no installer written");
  const zipPath = join(partial, `${base}.zip`);
  r = run(...winZipCommand({bundleDir: dirname(appPath), folderName: basename(appPath), zipPath}));
  if (r.status !== 0) return fail("ZIP_FAILED", String(r.status));

  const artefactReport = {
    flavour, platform: "win32", appName: report.appName, version: report.version, buildNumber: report.buildNumber,
    signed: false, appUserModelId, installerAppId: INSTALLER_APP_IDS[flavour],
    installer: {file: basename(installerPath), bytes: statSync(installerPath).size, sha256: sha256(installerPath)},
    zip: {file: basename(zipPath), bytes: statSync(zipPath).size, sha256: sha256(zipPath)}
  };
  writeFileSync(join(partial, "artefacts-report.json"), JSON.stringify(artefactReport, null, 2) + "\n");
  rmSync(artefactDir, {recursive: true, force: true});
  renameSync(partial, artefactDir);
  log(`ARTEFACTS_OK ${flavour} unsigned installer ${artefactReport.installer.bytes} zip ${artefactReport.zip.bytes} at ${artefactDir}`);
  return 0;
}

/** Where nfpm is: CLAVE_NFPM, else the usual install folders. */
function findNfpm(env, home) {
  const candidates = [env.CLAVE_NFPM, join(home, ".local", "bin", "nfpm"), "/usr/local/bin/nfpm", "/usr/bin/nfpm"];
  return candidates.find((p) => typeof p === "string" && existsSync(p)) ?? null;
}

/**
 * The Linux artefacts: a .deb and an .rpm made by nfpm from the fused app folder, each file list read
 * back and checked where this machine has the tool to read it (dpkg-deb on Ubuntu, rpm where
 * installed), and a SHA256SUMS beside them: on Linux the published checksums are the integrity check.
 * Made in a partial folder and renamed into place, as on the other systems.
 */
async function linuxArtefacts({appDir, out, flavour, report, env, home, log, fail}) {
  const decision = linuxArtefactDecision({flavour, report});
  if (decision.error) return fail(decision.error);
  const appPath = join(out.dir, report.appPath);
  if (typeof report.executable !== "string" || !existsSync(join(appPath, report.executable))) return fail("BUNDLE_MISSING", "app");
  const base = artefactBaseName(report, report.arch);
  if (base === null) return fail("BUNDLE_MISSING", "report fields");
  const dir = installDir(report.appName);
  if (dir === null) return fail("APP_NAME_UNSAFE");
  const desktopId = BUNDLE_IDS[flavour];
  const models = Array.isArray(report.models) ? report.models.map((m) => m.file) : [];
  if (models.length === 0) return fail("BUNDLE_MISSING", "models");
  const iconPath = join(appDir, "build", "icon-preview.png");
  const size = existsSync(iconPath) ? pngSize(readFileSync(iconPath)) : null;
  if (size === null || size.width !== 256 || size.height !== 256) return fail("ICON_MISSING", "app/build/icon-preview.png must be a 256x256 PNG");
  const nfpm = findNfpm(env, home);
  if (nfpm === null) return fail("NFPM_MISSING", `install nfpm ${NFPM.version} (checksums in scripts/package/linux/packages.mjs) or set CLAVE_NFPM`);
  // Depends, from what the app folder's binaries link (every ELF file's NEEDED entries, read with
  // readelf), minus what the folder ships itself; a library with no known package refuses the build.
  const readelf = ["/usr/bin/readelf", "/bin/readelf"].find(existsSync);
  if (!readelf) return fail("READELF_MISSING", "install binutils");
  const isElf = (path) => { const fd = openSync(path, "r"); try { const b = Buffer.alloc(4); return readSync(fd, b, 0, 4, 0) === 4 && b.equals(Buffer.from([0x7f, 0x45, 0x4c, 0x46])); } finally { closeSync(fd); } };
  const files = walk(appPath).filter((e) => e.kind === "file");
  const needed = [];
  for (const e of files) {
    if (!isElf(join(appPath, e.rel))) continue;
    const r = run(readelf, ["-d", join(appPath, e.rel)]);
    if (r.status !== 0) return fail("READELF_FAILED", e.rel);
    needed.push(...parseNeeded(r.stdout));
  }
  const depends = dependsFor({needed, bundled: files.map((e) => posix.basename(e.rel))});
  if (depends.unmapped.length > 0) return fail("SONAME_UNMAPPED", `${depends.unmapped.join(",")}: add it to SONAME_PACKAGES in scripts/package/linux/packages.mjs`);

  const version = run(nfpm, ["--version"]);
  const found = nfpmVersionOf(`${version.stdout}\n${version.stderr}`);
  if (found !== NFPM.version) return fail("NFPM_VERSION_WRONG", `found ${found ?? "unknown"}, need ${NFPM.version}`);

  const artefactDir = join(out.dir, flavour, "artefacts");
  const partial = join(out.dir, flavour, "artefacts.partial");
  rmSync(partial, {recursive: true, force: true});
  const inputs = join(partial, "package-inputs");
  mkdirSync(inputs, {recursive: true});
  const executablePath = `${dir}/${report.executable}`;
  const profileFile = join(inputs, desktopId);
  const desktopFile = join(inputs, `${desktopId}.desktop`);
  const postinstFile = join(inputs, "postinst");
  const prermFile = join(inputs, "prerm");
  try {
    writeFileSync(profileFile, apparmorProfile({profileName: desktopId, executablePath}), {mode: 0o644});
    writeFileSync(desktopFile, desktopEntry({appName: report.appName, desktopId, executablePath}), {mode: 0o644});
    writeFileSync(postinstFile, postinstScript({profilePath: `/etc/apparmor.d/${desktopId}`}), {mode: 0o755});
    writeFileSync(prermFile, prermScript({profilePath: `/etc/apparmor.d/${desktopId}`}), {mode: 0o755});
  } catch (error) { return fail(error instanceof Error ? error.message : "PACKAGE_INPUT_UNSAFE"); }
  for (const file of [postinstFile, prermFile]) chmodSync(file, 0o755);
  const decided = nfpmConfig({flavour, appName: report.appName, executable: report.executable, arch: report.arch, version: report.version, buildNumber: report.buildNumber,
    appDir: appPath, desktopFile, iconFile: iconPath, profileFile, postinstFile, prermFile, maintainer: env.CLAVE_COPYRIGHT_ENTITY ?? "Clave", depends: {deb: depends.deb, rpm: depends.rpm}});
  if (decided.error) return fail(decided.error);
  const configPath = join(inputs, "nfpm.json");
  writeFileSync(configPath, JSON.stringify(decided.config, null, 2) + "\n");

  const made = {};
  for (const kind of ["deb", "rpm"]) {
    const path = join(partial, `${base}.${kind}`);
    const r = run(nfpm, ["package", "--config", configPath, "--packager", kind, "--target", path]);
    if (r.status !== 0 || !existsSync(path)) {
      writeFileSync(join(partial, `nfpm-${kind}.log`), `${r.stdout}\n${r.stderr}`);
      return fail("PACKAGE_FAILED", `${kind}; see artefacts.partial/nfpm-${kind}.log`);
    }
    made[kind] = path;
  }

  // The file lists, read back by each format's own tool when this machine has it; a check that could
  // not run is recorded as not run, never as passed.
  const checks = {};
  const listingProblems = (kind, listed) => checkPackageListing({listed, kind, appName: report.appName, executable: report.executable, desktopId, models});
  if (existsSync("/usr/bin/dpkg-deb")) {
    const listing = run("/usr/bin/dpkg-deb", ["--contents", made.deb]);
    const debDepends = run("/usr/bin/dpkg-deb", ["--field", made.deb, "Depends"]).stdout.trim();
    const info = run("/usr/bin/dpkg-deb", ["--info", made.deb]).stdout;
    const problems = listing.status === 0 ? listingProblems("deb", parseDebListing(listing.stdout)) : [{code: "PACKAGE_UNREADABLE", detail: "deb"}];
    if (debDepends !== depends.deb.join(", ")) problems.push({code: "PACKAGE_DEPENDS_WRONG", detail: "deb"});
    for (const script of ["postinst", "prerm"]) if (!new RegExp(`\\s${script}\\s`).test(info)) problems.push({code: "PACKAGE_SCRIPT_MISSING", detail: script});
    checks.deb = {checked: true, problems};
  } else checks.deb = {checked: false};
  const rpmTool = ["/usr/bin/rpm", "/bin/rpm"].find(existsSync);
  if (rpmTool) {
    const listing = run(rpmTool, ["-qlvp", made.rpm]);
    const scripts = run(rpmTool, ["-qp", "--scripts", made.rpm]).stdout.trim();
    const problems = listing.status === 0 ? listingProblems("rpm", parseRpmListing(listing.stdout)) : [{code: "PACKAGE_UNREADABLE", detail: "rpm"}];
    if (scripts) problems.push({code: "PACKAGE_SCRIPT_UNEXPECTED", detail: "rpm"});
    checks.rpm = {checked: true, problems};
  } else checks.rpm = {checked: false};

  const entry = (path) => ({file: basename(path), bytes: statSync(path).size, sha256: sha256(path)});
  const artefactReport = {
    flavour, platform: "linux", arch: report.arch, appName: report.appName, version: report.version, buildNumber: report.buildNumber,
    signed: false, integrity: "sha256 checksums", nfpm: NFPM.version, installDir: dir, desktopId, depends: {deb: depends.deb, rpm: depends.rpm},
    deb: {...entry(made.deb), ...checks.deb}, rpm: {...entry(made.rpm), ...checks.rpm}
  };
  writeFileSync(join(partial, "artefacts-report.json"), JSON.stringify(artefactReport, null, 2) + "\n");
  const problems = [...(checks.deb.problems ?? []), ...(checks.rpm.problems ?? [])];
  if (problems.length > 0) return fail(problems[0].code, `${problems[0].detail} (+${problems.length - 1})`);
  writeFileSync(join(partial, "SHA256SUMS"), [artefactReport.deb, artefactReport.rpm].map((e) => `${e.sha256}  ${e.file}`).join("\n") + "\n");
  rmSync(inputs, {recursive: true, force: true});
  rmSync(artefactDir, {recursive: true, force: true});
  renameSync(partial, artefactDir);
  const checked = (kind) => (checks[kind].checked ? "checked" : "not checked here");
  log(`ARTEFACTS_OK ${flavour} linux-${report.arch} unsigned deb ${artefactReport.deb.bytes} (${checked("deb")}) rpm ${artefactReport.rpm.bytes} (${checked("rpm")}) at ${artefactDir}`);
  return 0;
}

export async function artefacts({appDir, argv, env, home, log, err}) {
  const fail = (code, detail) => { err(`ARTEFACTS_FAILED ${code}${detail ? ` ${detail}` : ""}`); return 1; };
  const out = resolveOut(argv, home, appDir);
  if (out.error) return fail(out.error);
  const asked = requestedFlavour(argv);
  if (asked.error) return fail(asked.error);
  if (asked.flavour === null) return fail("FLAVOUR_REQUIRED");
  const flavour = asked.flavour;
  const notarizeArg = parseNotarizeArg(argv);
  if (notarizeArg.error) return fail(notarizeArg.error);

  const bundleOut = join(out.dir, flavour, "bundle");
  const reportPath = join(bundleOut, "bundle-report.json");
  if (!existsSync(reportPath)) return fail("BUNDLE_MISSING", "run: pnpm --dir app package:bundle, then package:sign");
  let report;
  try { report = JSON.parse(readFileSync(reportPath, "utf8")); } catch { return fail("BUNDLE_MISSING"); }
  if (report.flavour !== flavour) return fail("BUNDLE_FLAVOUR_MISMATCH", report.flavour);
  if (report.platform === "win32") {
    if (notarizeArg.profile !== null) return fail("NOTARIZE_IS_MACOS_ONLY");
    return windowsArtefacts({appDir, out, flavour, report, env, log, fail});
  }
  if (report.platform === "linux") {
    if (notarizeArg.profile !== null) return fail("NOTARIZE_IS_MACOS_ONLY");
    return linuxArtefacts({appDir, out, flavour, report, env, home, log, fail});
  }
  const decision = notarizeDecision({flavour, report, profile: notarizeArg.profile});
  if (decision.error) return fail(decision.error);
  const appPath = join(out.dir, report.appPath);
  if (!existsSync(appPath)) return fail("BUNDLE_MISSING", "app");
  const base = artefactBaseName(report);
  if (base === null) return fail("BUNDLE_MISSING", "report fields");

  // Everything is made in a PARTIAL folder and renamed into place only at the end: a failed run leaves
  // the previous artefacts alone and nothing half-made under the final name. The app copy for the
  // DMG lives inside it too, so it is removed with it whatever happens.
  const artefactDir = join(out.dir, flavour, "artefacts");
  const partial = join(out.dir, flavour, "artefacts.partial");
  const dmgRoot = join(partial, "dmg-root");
  rmSync(partial, {recursive: true, force: true});
  mkdirSync(dmgRoot, {recursive: true});
  const dmgPath = join(partial, `${base}.dmg`);
  const zipPath = join(partial, `${base}.zip`);
  const notarized = !decision.skip;
  const notary = {app: null, dmg: null};
  const saveText = (name, text) => writeFileSync(join(partial, name), String(text ?? "").split("\r\n").join("\n"));

  try {
    // 1. The .app: notarised and stapled in place (the profile name is all @electron/notarize is given).
    //    Its error carries notarytool's own log for a rejection: saved whole, then the run refuses.
    if (notarized) {
      const mod = await loadNotarize();
      try { await mod.notarize({appPath, keychainProfile: decision.profile}); notary.app = "Accepted"; }
      catch (error) {
        saveText("notary-app.log", error instanceof Error ? `${error.message}\n${error.stack ?? ""}` : String(error));
        return fail("NOTARIZE_FAILED", "see artefacts.partial/notary-app.log");
      }
    }

    // 2. The DMG: a folder with the app (copied by ditto, which keeps symlinks, modes, signatures and
    //    the stapled ticket) and an Applications link, so a drag installs it and translocation never applies.
    const destApp = join(dmgRoot, basename(appPath));
    let r = run(...copyAppCommand({appPath, destAppPath: destApp}));
    if (r.status !== 0) return fail("DMG_COPY_FAILED", String(r.status));
    symlinkSync("/Applications", join(dmgRoot, "Applications"));
    r = run(...dmgCommand({root: dmgRoot, volumeName: report.appName, dmgPath}));
    if (r.status !== 0) return fail("DMG_CREATE_FAILED", String(r.status));
    r = run(...signDmgCommand({identity: report.identity, dmgPath}));
    if (r.status !== 0) return fail("DMG_SIGN_FAILED", String(r.status));
    if (notarized) {
      r = run(...notarySubmitCommand({path: dmgPath, profile: decision.profile}));
      const result = notaryResult(`${r.stdout}\n${r.stderr}`);
      saveText("notary-dmg-submit.log", `${r.stdout}\n${r.stderr}`);
      if (result.id) {
        const logResult = run(...notaryLogCommand({id: result.id, profile: decision.profile}));
        saveText("notary-dmg.log", `${logResult.stdout}\n${logResult.stderr}`);
      }
      notary.dmg = {status: result.status, id: result.id};
      if (r.status !== 0 || result.status !== "Accepted") return fail("DMG_NOTARIZE_FAILED", result.status ?? String(r.status));
      r = run(...stapleCommand(dmgPath));
      if (r.status !== 0) return fail("DMG_STAPLE_FAILED", String(r.status));
    }

    // 3. The ZIP of the (stapled) app.
    r = run(...zipCommand({appPath, zipPath}));
    if (r.status !== 0) return fail("ZIP_FAILED", String(r.status));

    // 4. The checks, every one recorded; the ones that must pass, enforced. The signature chain of the
    //    app, its helper and the DMG is recorded too (authority names and the team identifier only).
    const results = checkPlan({appPath, dmgPath, developerId: report.developerId === true, notarized}).map((c) => ({name: c.name, mustPass: c.mustPass, status: run(c.cmd, c.args).status}));
    const chain = (path) => signatureChain(run("/usr/bin/codesign", ["-dvv", path]).stderr);
    const problems = checkProblems(results);
    const artefactReport = {
      flavour, appName: report.appName, version: report.version, buildNumber: report.buildNumber, identity: report.identity, developerId: report.developerId === true, notarized, notary,
      dmg: {file: basename(dmgPath), bytes: statSync(dmgPath).size, sha256: sha256(dmgPath)},
      zip: {file: basename(zipPath), bytes: statSync(zipPath).size, sha256: sha256(zipPath)},
      signatures: {app: chain(appPath), helper: chain(join(appPath, "Contents", "MacOS", "clave-reader")), dmg: chain(dmgPath)},
      checks: results
    };
    writeFileSync(join(partial, "artefacts-report.json"), JSON.stringify(artefactReport, null, 2) + "\n");
    if (problems.length > 0) return fail(problems[0].code, `${problems[0].detail} (+${problems.length - 1})`);
    rmSync(dmgRoot, {recursive: true, force: true});
    rmSync(artefactDir, {recursive: true, force: true});
    renameSync(partial, artefactDir);
    log(`ARTEFACTS_OK ${flavour} ${notarized ? "notarized" : "not notarized"} dmg ${artefactReport.dmg.bytes} zip ${artefactReport.zip.bytes} at ${artefactDir}`);
    return 0;
  } finally {
    rmSync(dmgRoot, {recursive: true, force: true});
  }
}

if (process.argv[1] && posix.basename(process.argv[1].split("\\").join("/")) === "artefacts.mjs") {
  const appDir = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
  artefacts({appDir, argv: process.argv, env: process.env, home: homedir(), log: console.log, err: console.error}).then((code) => process.exit(code));
}
